Fix missing-prototypes
lib/screenshooter-imgur-dialog.c:205:1: error: no previous prototype for 'screenshooter_imgur_dialog_run' [-Werror=missing-prototypes]

Signed-off-by: Olaf Hering <olaf@aepfle.de>